### ISSUE TITLE
[BUG] [MAJOR] CPU Reset Routine doesn't work, gets stuck.

### ISSUE THREAD

**Issue by Evanito** [bencbartlett/Overmind#65] opened 2019-01-07 22:50 UTC
## Issue summary
Overmind gets stuck looping
`WARNING 3139967 CPU bucket is critically low (13)! Starting CPU reset routine.`
### Description of issue:

When Overmind is running out of CPU, it tries to go into CPU reset routine. It never actually goes into it (?) and just tries again every tick, draining CPU the whole time.
Occasionally I see that it used the max CPU time limit several ticks in a row, and that's how it gets to a low number quickly.

After manually pausing the script until enough CPU is saved up, I get:
`INFO    3140278 Operation suspended until bucket recovery. Bucket: 5520/10000`
which seems to be normal behavior

This is on Shard 3
### Steps to reproduce:

This has occurred twice:
- I was tired of a colony that was in "terminal evacuate" mode for some reason, so I unclaimed it. Overmind immediately spent a lot of CPU doing who knows what (saw the room builder flash for a tick) and got stuck at low CPU (~200, decreasing slowly.) Saved by flushing memory and errant flags, and bypassing execution until bucket was at a safe level.
- Now that I had a new room slot, Overmind colonized another room while I was away. Spawn and some extenders were built and RCL was 2, so it likely didn't happen immediately. Saved by bypassing execution until bucket was at a safe level.

### Error message:

```
// Console output:
WARNING 3139967 CPU bucket is critically low (13)! Starting CPU reset routine.
WARNING 3139968 CPU bucket is critically low (11)! Starting CPU reset routine.
...etc
After manually pausing the script until enough CPU is saved up:
INFO    3140278 Operation suspended until bucket recovery. Bucket: 5520/10000
```

```
// Offending line:

```

### Other information:
- Overmind version: v0.5.1
    - Commit hash:

**Comment by bencbartlett** [comment] 2019-01-29 21:03
This should be fixed as of [this commit](https://github.com/bencbartlett/Overmind/commit/2b914ca73effa3f97dd7cbd249dda8bb33ba834f). Feel free to reopen the issue if it is still a problem.

**Comment by Evanito** [comment] 2019-01-29 22:30
Not fixed as intended. 
While it no longer gets stuck at 0 CPU, I get a `CPU Halted.` red error message in console about the time that it would report getting 500 CPU in the bucket, which puts it back below 500 and the cycle repeats. If I manually pause until it exceeds 500CPU (say, 1000) then it will not get this error.

Also I am unable to reopen this issue, I assume because of GitHub permissions.

**Comment by Evanito** [comment] 2019-01-29 22:33
To clarify, the only output it shows is
```
[2:31:46 PM][shard3]INFO    3781874 Operation suspended until bucket recovery. Bucket: 496/10000
CPU Halted.
[2:31:4X PM][shard3]INFO    378187X Operation suspended until bucket recovery. Bucket: 472/10000
[2:31:5X PM][shard3]INFO    378187X Operation suspended until bucket recovery. Bucket: 487/10000
```

**Comment by bencbartlett** [comment] 2019-01-30 01:42
Ah, that is unintended behavior. I'll look into it again.

**Comment by mlinky** [comment] 2019-02-21 07:58
This is also happening to me now that I am at GCL 3 on shard 3. The colonies have no creeps and the log file is exactly as above.

**Comment by bencbartlett** [comment] 2019-02-22 00:58
Sorry this has taken so long to get around to; I've been pretty busy the last two weeks. Here is how I understand this bug: I added `Game.cpu.halt()` to the CPU reset routine to fix some weird heap issues that I have been experiencing on shard2. However, in low-CPU environments like shard3, the amount of CPU you accumulate per tick is less than the cost of parsing the ~1MB `main.js` file on the tick following `Game.cpu.halt()`. This can cause the bucket to dip back below the CPU-reset threshold, causing the endless cycle of CPU resets. I have pushed a short fix in the latest commit which should fix this problem, but I'll leave this issue open until @Evanito and/or @mlinky can confirm that the problem is no longer an issue.

**Comment by Evanito** [comment] 2019-02-22 01:39
It may be conflated with a related problem: Running two colonies (8[2 outposts]/7[5 outposts]) on shard3 puts me at 75% CPU consistently. This does not leave enough for a third potential colony, but one is formed anyway and drains the bucket.

Potential solution: Calculate max colonies based on average CPU usage per colony instead of the hard 3 for shard3?

I solved my death spiral by entering semiautomatic and abandoning my third colony, when I have time to micromanage I will purposefully test the new commit.

**Comment by mlinky** [comment] 2019-02-22 11:04
Hi,

I've made a small change to my script and it now behaves a lot better

Inside:

    static shouldRun() {

I have added:

        if (Game.cpu.bucket < 5000) {
            // Additional failsafe for bucket depletion
            log.warning(`CPU bucket is getting low (${Game.cpu.bucket})! Starting CPU reset routine.`);
            Memory.resetBucket = true;
        }

Above:

        if (Memory.resetBucket) {
            if (Game.cpu.bucket < MAX_BUCKET - Game.cpu.limit) {
                log.info(`Operation suspended until bucket recovery. Bucket: ${Game.cpu.bucket}/${MAX_BUCKET}`);
                shouldRun = false;
            }
            else {
                delete Memory.resetBucket;
            }
        }

The script now halts all processing when the bucket reaches 5,000 and waits for it to replenish to 10,000.

Will look at the your fix now too!!

Thanks for looking into this.

**Comment by bencbartlett** [comment] 2019-02-22 18:33
@mlinky I think that change conflicts with some of the other changes I have made to `Mem` recently, but if it works for you, that's great. However, can you test fix I pushed recently as-is, without any modifications, and let me know if it works? If so, then I can finally close this issue. Thanks!

**Comment by mlinky** [comment] 2019-02-22 20:09
With your fix in place it no longer falls into a terminal loop. So the fix is good. The console message is still misleading, it says postponing operations until bucket reaches 500, but really nothing happens until the bucket reaches 10000.

**Comment by mlinky** [comment] 2019-02-23 11:04
Watching this run through, I'm wondering if recovering 9500 bucket while all your creeps sit and decay is a good plan? Maybe only recovering 20 per tick on shard3 is part of the problem? Seems like the long delay means that most colonies are needing to respawn creeps to recover from the extended downtime instead of just carrying on with business. 
Is it possible that the trigger level for the bucket should be in proportion to the amount that can be recovered per tick instead?

**Comment by bencbartlett** [comment] 2019-02-27 02:31
@mlinky Glad to hear the bug is fixed now. The bucket recovery strategy was designed for use in shard2 and probably isn't the best idea for shard3. I plan to improve this later, once I establish a foothold in shard3, but feel free to make a separate issue if you find the current bucket recovery system problematic.

**Closed by bencbartlett** 2019-02-27 02:31 UTC
Labels: CPU / performance, bug, high priority
